/*
BST Generic Project
April 2023
Ella Chi

Class: GUI (main class)
creates user interface and provides main functinality for the code
runs the program
handles errors from user input
 */
import java.util.*;
import javax.swing.*;
import java.io.*;

public class GUI extends javax.swing.JFrame {
    private static BST<VocabEntry> vocab = new BST<VocabEntry>();
    private static VocabEntry currentWord;
    private static DefaultListModel<VocabEntry> lst = new DefaultListModel<>();
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        
        //set size and layout
        setLayout(null);
        pnlStudy.setLayout(null);
        setSize(560, 360);
        
        lstDisplay.setModel(lst);
                pnlHome.add(sclList);

        pnlDef.setVisible(false);
        pnlStudy.setVisible(false);
        pnlNewWord.setVisible(false);
        pnlEdit.setVisible(false);
        sclList.setVisible(false);
        
        pnlHome.setLocation(0,0);
        sclTree.setLocation(0,0);
        pnlNewWord.setLocation(pnlHome.getLocation());
        pnlStudy.setLocation(pnlHome.getLocation());
        pnlDef.setLocation(pnlWord.getLocation());
        sclList.setLocation(0,0);
        pnlEdit.setLocation(pnlHome.getLocation());
        
        sclList.setSize(sclTree.getSize());
        txtDisplay.setEditable(false);
        
        updateDisplay();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        pnlNewWord = new javax.swing.JPanel();
        txtNewWord = new javax.swing.JTextField();
        lblNewWord = new javax.swing.JLabel();
        lblNewDef = new javax.swing.JLabel();
        btnConfirmNew = new javax.swing.JButton();
        btnCancelNew = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNewDef = new javax.swing.JTextArea();
        lblStudied = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        spnTotal = new javax.swing.JSpinner();
        spnCorrect = new javax.swing.JSpinner();
        lblAdd = new javax.swing.JLabel();
        pnlStudy = new javax.swing.JPanel();
        btnKnow = new javax.swing.JButton();
        btnDontKnow = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnRemoveCur = new javax.swing.JButton();
        pnlWord = new javax.swing.JPanel();
        lblStudyW = new javax.swing.JLabel();
        lblDisplayWord = new javax.swing.JLabel();
        lblAvg = new javax.swing.JLabel();
        pnlDef = new javax.swing.JPanel();
        lblStudyD = new javax.swing.JLabel();
        lblDisplayDef = new javax.swing.JLabel();
        btnFlip = new javax.swing.JButton();
        btnEditCur = new javax.swing.JButton();
        btnSkip = new javax.swing.JButton();
        pnlEdit = new javax.swing.JPanel();
        lblEdit = new javax.swing.JLabel();
        txtEditWord = new javax.swing.JTextField();
        lblEditWord = new javax.swing.JLabel();
        lblEditDef = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtEditDef = new javax.swing.JTextArea();
        btnConfirmEdit = new javax.swing.JButton();
        btnCancelEdit = new javax.swing.JButton();
        pnlHome = new javax.swing.JLayeredPane();
        btnRevSel = new javax.swing.JButton();
        btnRev = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        sclTree = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();
        lblTotal = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        chkDisplayList = new javax.swing.JCheckBox();
        btnWorst = new javax.swing.JButton();
        btnBest = new javax.swing.JButton();
        sclList = new javax.swing.JScrollPane();
        lstDisplay = new javax.swing.JList<>();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Study Vocabulary");

        pnlNewWord.setPreferredSize(new java.awt.Dimension(539, 326));

        lblNewWord.setText("Word:");

        lblNewDef.setText("Definition: ");

        btnConfirmNew.setText("Confirm");
        btnConfirmNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmNewActionPerformed(evt);
            }
        });

        btnCancelNew.setText("Cancel");
        btnCancelNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewActionPerformed(evt);
            }
        });

        txtNewDef.setColumns(20);
        txtNewDef.setRows(5);
        jScrollPane3.setViewportView(txtNewDef);

        lblStudied.setText("How many times have you studied this word?");

        lblCorrect.setText("How many times have you gotten it right?");

        spnTotal.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spnCorrect.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblAdd.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblAdd.setText("New Word:");

        javax.swing.GroupLayout pnlNewWordLayout = new javax.swing.GroupLayout(pnlNewWord);
        pnlNewWord.setLayout(pnlNewWordLayout);
        pnlNewWordLayout.setHorizontalGroup(
            pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewWordLayout.createSequentialGroup()
                .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewWordLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNewWordLayout.createSequentialGroup()
                                .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNewDef)
                                    .addComponent(lblNewWord))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNewWord)
                                    .addComponent(jScrollPane3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNewWordLayout.createSequentialGroup()
                                .addComponent(btnCancelNew, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConfirmNew))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNewWordLayout.createSequentialGroup()
                                .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStudied)
                                    .addComponent(lblCorrect))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(spnCorrect, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlNewWordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        pnlNewWordLayout.setVerticalGroup(
            pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewWordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewWord)
                    .addComponent(txtNewWord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewDef)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudied)
                    .addComponent(spnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorrect)
                    .addComponent(spnCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNewWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmNew)
                    .addComponent(btnCancelNew, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pnlStudy.setPreferredSize(new java.awt.Dimension(539, 326));

        btnKnow.setText("Know this");
        btnKnow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKnowActionPerformed(evt);
            }
        });

        btnDontKnow.setText("Don't know this");
        btnDontKnow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDontKnowActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnRemoveCur.setText("Remove Word");
        btnRemoveCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCurActionPerformed(evt);
            }
        });

        lblStudyW.setText("(Word)");

        lblDisplayWord.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblDisplayWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisplayWord.setText("WORD");

        lblAvg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvg.setText("Average Score: ");

        javax.swing.GroupLayout pnlWordLayout = new javax.swing.GroupLayout(pnlWord);
        pnlWord.setLayout(pnlWordLayout);
        pnlWordLayout.setHorizontalGroup(
            pnlWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWordLayout.createSequentialGroup()
                .addGroup(pnlWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStudyW))
                    .addGroup(pnlWordLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lblDisplayWord))
                    .addGroup(pnlWordLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        pnlWordLayout.setVerticalGroup(
            pnlWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudyW)
                .addGap(84, 84, 84)
                .addComponent(lblDisplayWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(lblAvg)
                .addContainerGap())
        );

        pnlDef.setPreferredSize(new java.awt.Dimension(485, 248));

        lblStudyD.setText("(Definition)");

        lblDisplayDef.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblDisplayDef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisplayDef.setText("definition");

        javax.swing.GroupLayout pnlDefLayout = new javax.swing.GroupLayout(pnlDef);
        pnlDef.setLayout(pnlDefLayout);
        pnlDefLayout.setHorizontalGroup(
            pnlDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDefLayout.createSequentialGroup()
                .addGroup(pnlDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDefLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStudyD))
                    .addGroup(pnlDefLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDisplayDef, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlDefLayout.setVerticalGroup(
            pnlDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDefLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudyD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDisplayDef, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnFlip.setText("View Definition");
        btnFlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlipActionPerformed(evt);
            }
        });

        btnEditCur.setText("Edit Word");
        btnEditCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCurActionPerformed(evt);
            }
        });

        btnSkip.setText("Skip Word");
        btnSkip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStudyLayout = new javax.swing.GroupLayout(pnlStudy);
        pnlStudy.setLayout(pnlStudyLayout);
        pnlStudyLayout.setHorizontalGroup(
            pnlStudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStudyLayout.createSequentialGroup()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveCur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditCur, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSkip, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStudyLayout.createSequentialGroup()
                        .addComponent(btnDontKnow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFlip, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKnow, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStudyLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(pnlWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19123, Short.MAX_VALUE)
                .addComponent(pnlDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlStudyLayout.setVerticalGroup(
            pnlStudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudyLayout.createSequentialGroup()
                .addGroup(pnlStudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStudyLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(pnlWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlStudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFlip)
                            .addComponent(btnKnow)
                            .addComponent(btnDontKnow)))
                    .addGroup(pnlStudyLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(pnlDef, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlStudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnRemoveCur)
                    .addComponent(btnEditCur)
                    .addComponent(btnSkip))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEdit.setPreferredSize(new java.awt.Dimension(539, 326));

        lblEdit.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblEdit.setText("Edit Word");

        lblEditWord.setText("New Word:");

        lblEditDef.setText("New Definition: ");

        txtEditDef.setColumns(20);
        txtEditDef.setRows(5);
        jScrollPane5.setViewportView(txtEditDef);

        btnConfirmEdit.setText("Confirm");
        btnConfirmEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmEditActionPerformed(evt);
            }
        });

        btnCancelEdit.setText("Cancel");
        btnCancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addComponent(lblEdit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditLayout.createSequentialGroup()
                                .addComponent(btnCancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConfirmEdit))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(txtEditWord, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEditWord)
                                    .addComponent(lblEditDef))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(111, 111, 111))))
        );
        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lblEditWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditWord, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEditDef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmEdit))
                .addGap(44, 44, 44))
        );

        btnRevSel.setText("Review Selected");
        btnRevSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevSelActionPerformed(evt);
            }
        });

        btnRev.setText("Review All");
        btnRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevActionPerformed(evt);
            }
        });

        btnQuit.setText("Exit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        txtDisplay.setEnabled(false);
        sclTree.setViewportView(txtDisplay);

        lblTotal.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0 words total");

        btnAdd.setText("Add Word");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Word");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove Selected");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        chkDisplayList.setText("Display List");
        chkDisplayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDisplayListActionPerformed(evt);
            }
        });

        btnWorst.setText("Worst Word");
        btnWorst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorstActionPerformed(evt);
            }
        });

        btnBest.setText("Best Word");
        btnBest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestActionPerformed(evt);
            }
        });

        pnlHome.setLayer(btnRevSel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlHome.setLayer(btnRev, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlHome.setLayer(btnQuit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlHome.setLayer(sclTree, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlHome.setLayer(lblTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlHome.setLayer(btnAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlHome.setLayer(btnEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlHome.setLayer(btnRemove, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlHome.setLayer(chkDisplayList, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlHome.setLayer(btnWorst, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlHome.setLayer(btnBest, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sclTree, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBest, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkDisplayList, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRevSel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnWorst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRevSel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWorst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDisplayList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuit))
                    .addComponent(sclTree, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(345, 345, 345))
        );

        lstDisplay.setPreferredSize(new java.awt.Dimension(100, 100));
        sclList.setViewportView(lstDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStudy, javax.swing.GroupLayout.PREFERRED_SIZE, 20165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlNewWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sclList, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sclList, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addComponent(pnlNewWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(pnlStudy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //open panel to get user input for new word
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        pnlNewWord.setVisible(true);
        pnlHome.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    //create new entry based on user input and add to tree
    private void btnConfirmNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmNewActionPerformed
        //retrieve input values for the vocab entry
        String w = txtNewWord.getText().toLowerCase();
        String d = txtNewDef.getText();
        int total = (Integer)spnTotal.getValue();
        int correct = (Integer)spnCorrect.getValue();
        
        //check that string values for word and definition are not blank
        if(w.equals("") || d.equals("")){
            //if at least one is blank,  output error and do not add
            JOptionPane.showMessageDialog(rootPane, "Make sure you input values for both the word and definition");
            return;
        } 
        
        //check that the total times studied is greater than/equal to the amount it was correct
        if(total < correct){
            JOptionPane.showMessageDialog(rootPane, "The number of times correct should be less than or equal to the total times studied.");
            return;
        }
        
        //check if word is already in bank, if it is, don't add the new word
        if (!vocab.contains(w)){
        
            //add to new entry to list
            vocab.addBalanced(new VocabEntry(w, d, correct, total));

            //update the list view
            List<VocabEntry> updated = vocab.toList();
            for(VocabEntry v : updated){
                lst.addElement(v);
            }
            
            lblTotal.setText(vocab.size() + " words total");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vocabulary word already exists in the tree");
        }
        
//        System.out.println(vocab.toList().toString());
        lstDisplay.setListData(vocab.toList().toArray(new VocabEntry[vocab.size()]));
        
        txtDisplay.setText(vocab.display());
                
        //rexit and eturn to home page
        pnlNewWord.setVisible(false);
        pnlHome.setVisible(true);
        
        //reset input values
        txtNewWord.setText("");
        txtNewDef.setText("");
        spnTotal.setValue(0);
        spnCorrect.setValue(0);

    }//GEN-LAST:event_btnConfirmNewActionPerformed

    //return to home page
    private void btnCancelNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewActionPerformed
        pnlNewWord.setVisible(false);
        pnlHome.setVisible(true);
    }//GEN-LAST:event_btnCancelNewActionPerformed

    
    //remove the current word from tree
    private void btnRemoveCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCurActionPerformed
        //delete word
        vocab.delete(currentWord);
        System.out.println(vocab.display());
        
        //get index of deleted word
        int ind = lstDisplay.getSelectedIndex();
        
        //remove deleted word from list view
        lst.removeElement(currentWord);
        lblTotal.setText(vocab.size() + " words total");
        
        //display next word
        if(lst.indexOf(ind) < lst.size()){
            currentWord = lst.get(ind);
        } else {
            //error message if there is no next word --> returns home
            JOptionPane.showMessageDialog(rootPane, "You have reached the end of the study deck.");
            pnlStudy.setVisible(false);
            pnlHome.setVisible(true);
        }
        
        //update the display with updated tree
        updateDisplay();

    }//GEN-LAST:event_btnRemoveCurActionPerformed

    //return to home page
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        pnlStudy.setVisible(false);
        pnlHome.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    //flip the flashcard - i.e. display definition if looking at word and vice versa
    private void btnFlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlipActionPerformed
        if(pnlWord.isVisible()){
            //if word is currently visible, display definition
            pnlWord.setVisible(false);
            pnlDef.setVisible(true);
            btnFlip.setText("View Word");
        } else {
            //if definition is visible, display word
            pnlDef.setVisible(false);
            pnlWord.setVisible(true);
            btnFlip.setText("View Definition");
        }
    }//GEN-LAST:event_btnFlipActionPerformed

    //user knows this word --> update how many times the user has studied and known this word
    //move to next word
    private void btnKnowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKnowActionPerformed
        currentWord.updateCorrect();
        currentWord.updateTotal();
        
        //delete word from bst and balance the tree
        vocab.delete(currentWord);
        vocab.addBalanced(currentWord);
        
        //update display and move to next word
        updateDisplay();
        nextWord();
    }//GEN-LAST:event_btnKnowActionPerformed

    //user studied but doesn't know this word --> update how many times the user has studied and known this word
    //move to next word
    private void btnDontKnowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDontKnowActionPerformed
        currentWord.updateTotal();
        
        //re-sort and balance tree
        vocab.delete(currentWord);
        vocab.addBalanced(currentWord);

        //update display with updated tree and move to next word
        updateDisplay();
        nextWord();
    }//GEN-LAST:event_btnDontKnowActionPerformed

    //toggle between list and tree displays
    private void chkDisplayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDisplayListActionPerformed
        if(chkDisplayList.isSelected()){
            //if check box is selected, hide tree and display list
            sclTree.setVisible(false);
            sclList.setVisible(true);
            lstDisplay.setVisible(true);
            sclList.setLocation(sclTree.getLocation());
//            lstDisplay.setLocation(0,0);
        } else {
            //otherwise, hide list and display tree
            sclTree.setVisible(true);
            txtDisplay.setVisible(true);
            sclList.setVisible(false);
            lstDisplay.setVisible(false);
        }
    }//GEN-LAST:event_chkDisplayListActionPerformed

    //removes the selected word from the bst
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if(!chkDisplayList.isSelected()){
            //error if not in list view
            JOptionPane.showMessageDialog(rootPane, "To remove a word, please select it from the list in list view.");
            return;
        }
        
        int ind = lstDisplay.getSelectedIndex();
        if(ind < 0){
            //error if no word is selected
            JOptionPane.showMessageDialog(rootPane, "Please select a word to remove");
        } else {
            //delete the selected word from the tree and list and update the display accordingly
            currentWord = lst.get(ind);
            vocab.delete(currentWord);
            lst.remove(ind);
            lblTotal.setText(vocab.size() + " words total");
            updateDisplay();

        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    //confirms the edit and replaces the value of the current entry in the tree
    private void btnConfirmEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmEditActionPerformed
        //store inputted values
        String w = txtEditWord.getText();
        String d = txtEditDef.getText();
        
        //check that string values for word and definition are not blank
        if(w.equals("") || d.equals("")){
            //if at least one is blank,  output error and do not add
            JOptionPane.showMessageDialog(rootPane, "Make sure you input values for both the word and definition");
            return;
        } 
        
        //create new vocab entry and replace the element
        VocabEntry v = new VocabEntry(w,d,currentWord.getCorrect(), currentWord.getTotal());
        vocab.edit(currentWord, v);
        
        //update display tree and list with new value
        updateDisplay();
        
        //reset edit page
        txtEditWord.setText("");
        txtEditDef.setText("");
        
        //return home
        pnlEdit.setVisible(false);
        pnlHome.setVisible(true);
        currentWord = null;
    }//GEN-LAST:event_btnConfirmEditActionPerformed

    //returns home
    private void btnCancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditActionPerformed
        pnlEdit.setVisible(false);
        pnlHome.setVisible(true);
    }//GEN-LAST:event_btnCancelEditActionPerformed

    //opens the selected word to study
    private void btnRevSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevSelActionPerformed
        if(!chkDisplayList.isSelected()){
            //error if not in list view
            JOptionPane.showMessageDialog(rootPane, "To select a word, please select it from the list in list view.");
            return;
        }
        
        int ind = lstDisplay.getSelectedIndex();
        if(ind < 0){
            //error if no word is selected
            JOptionPane.showMessageDialog(rootPane, "Please select a word ");
            return;
        } 
        
        //opens study panel to display selected word
        pnlHome.setVisible(false);
        pnlStudy.setVisible(true);
        currentWord = lstDisplay.getSelectedValue();
        updateWord();
    }//GEN-LAST:event_btnRevSelActionPerformed

    //open edit page
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if(!chkDisplayList.isSelected()){
            //error if in tree view
            JOptionPane.showMessageDialog(rootPane, "To edit a word, please select it from the list in list view.");
            return;
        }
        
        int ind = lstDisplay.getSelectedIndex();
        if(ind < 0){
            //error if no word is selected
            JOptionPane.showMessageDialog(rootPane, "Please select a word to edit");
            return;
        } 
        
        //open edit panel to edit selected word
        pnlHome.setVisible(false);
        pnlEdit.setVisible(true);
        currentWord = lstDisplay.getSelectedValue();
    }//GEN-LAST:event_btnEditActionPerformed

    //allow viewer to look at words (and definitons) to study starting from least known --> open study page and display first word
    private void btnRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevActionPerformed
        if(vocab.isEmpty()){
            //display error if bst is empty
            JOptionPane.showMessageDialog(rootPane, "You have no words to study");
            return;
        }
        //study from minimum 
        currentWord = vocab.min();
        updateWord();
        
        //open study panel
        pnlHome.setVisible(false);
        pnlStudy.setVisible(true);
    }//GEN-LAST:event_btnRevActionPerformed

    //open edit panel to edit the value of current word
    private void btnEditCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCurActionPerformed
        pnlStudy.setVisible(false);
        pnlEdit.setVisible(true);
    }//GEN-LAST:event_btnEditCurActionPerformed

    //move on to next word and display
    private void btnSkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipActionPerformed
        nextWord();
       
        {
         }    }//GEN-LAST:event_btnSkipActionPerformed

    //quit program
    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    //display the minimum/worst word to review
    private void btnWorstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorstActionPerformed
        pnlHome.setVisible(false);
        pnlStudy.setVisible(true);
        currentWord = vocab.min();  
        updateWord();
    }//GEN-LAST:event_btnWorstActionPerformed

    //display the maximum/best word to review
    private void btnBestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestActionPerformed
        pnlHome.setVisible(false);
        pnlStudy.setVisible(true);
        currentWord = vocab.max();  
        updateWord();
    }//GEN-LAST:event_btnBestActionPerformed
    
    //update study display to display current word and definition
    private void updateWord(){
        lblDisplayWord.setText(currentWord.getWord());
        lblDisplayDef.setText(currentWord.getDef());
        lblAvg.setText("Average Score: " + currentWord.percent() + "%");
    }
    
    // moves to next word
    private void nextWord(){
        int curInd = lst.indexOf(currentWord);
        
        //if there is next word
        if(curInd+1 < vocab.size()){
            //set current word to the next word and update study display
            currentWord = lst.getElementAt(curInd + 1);
//            System.out.println(currentWord);
            updateWord();
        } else {
            //if no more words, display error and return home
            JOptionPane.showMessageDialog(rootPane, "You have reached the end of the study deck.");
            currentWord = null;
            pnlStudy.setVisible(false);
            pnlHome.setVisible(true);
        }
    }
    
    //updates the tree and list display to match changes to tree
    private void updateDisplay(){
        txtDisplay.setText(vocab.display());
        
        //add elements to list
        List<VocabEntry> updated = vocab.toList();
        lst.removeAllElements();
            for(VocabEntry v : updated){
                lst.addElement(v);
            }
            
        //update total number of words
        lblTotal.setText(vocab.size() + " words total");

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //create bst from text file
        try{
        Scanner in = new Scanner( new FileReader("/Users/ellachi/NetBeansProjects/BSTProject/src/words.txt") );
        String line;
        while (in.hasNextLine()){
            line = in.nextLine();
            line = line.trim();
            String[] arr = line.split(",");
            if (arr.length != 4){
                continue;
            }
            vocab.addBalanced(new VocabEntry(arr[0], arr[1], Integer.parseInt(arr[2]), Integer.parseInt(arr[3])));
//            System.out.println(vocab.display());
        }
        }catch (Exception e){
            System.out.println(e);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBest;
    private javax.swing.JButton btnCancelEdit;
    private javax.swing.JButton btnCancelNew;
    private javax.swing.JButton btnConfirmEdit;
    private javax.swing.JButton btnConfirmNew;
    private javax.swing.JButton btnDontKnow;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditCur;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFlip;
    private javax.swing.JButton btnKnow;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRemoveCur;
    private javax.swing.JButton btnRev;
    private javax.swing.JButton btnRevSel;
    private javax.swing.JButton btnSkip;
    private javax.swing.JButton btnWorst;
    private javax.swing.JCheckBox chkDisplayList;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblAvg;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblDisplayDef;
    private javax.swing.JLabel lblDisplayWord;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblEditDef;
    private javax.swing.JLabel lblEditWord;
    private javax.swing.JLabel lblNewDef;
    private javax.swing.JLabel lblNewWord;
    private javax.swing.JLabel lblStudied;
    private javax.swing.JLabel lblStudyD;
    private javax.swing.JLabel lblStudyW;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<VocabEntry> lstDisplay;
    private javax.swing.JPanel pnlDef;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JLayeredPane pnlHome;
    private javax.swing.JPanel pnlNewWord;
    private javax.swing.JPanel pnlStudy;
    private javax.swing.JPanel pnlWord;
    private javax.swing.JScrollPane sclList;
    private javax.swing.JScrollPane sclTree;
    private javax.swing.JSpinner spnCorrect;
    private javax.swing.JSpinner spnTotal;
    private javax.swing.JTextArea txtDisplay;
    private javax.swing.JTextArea txtEditDef;
    private javax.swing.JTextField txtEditWord;
    private javax.swing.JTextArea txtNewDef;
    private javax.swing.JTextField txtNewWord;
    // End of variables declaration//GEN-END:variables
}
